geometry:
  detect:
    min_area_ratio: 0.001
    aspect_range: [0.40, 3.00]
    max_quad_epsilon: 0.08
    min_solidity: 0.75
    feature:
      nfeatures: 2000
      match_ratio: 0.85
      ransac_thresh: 5.0
      min_inliers: 8
    prefer: "contours"
    debug: true
