canonical: {width: 744, height: 1039}

templates:
  modern_m15:
    selector: {holo_stamp: true}
    rois:
      collector_line: [0.050, 0.925, 0.456, 0.975]

  pre_m15:
    selector: {holo_stamp: false}
    rois:
      collector_line: [0.060, 0.910, 0.460, 0.965]
